[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Configuración específica para funciones
[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@supabase/supabase-js"]

# Aumentar el tiempo de timeout para funciones API
[functions."api/*"]
  timeout = 30

# Configuración de redirecciones para SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Redirecciones específicas para rutas de autenticación
[[redirects]]
  from = "/login"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/dashboard/*"
  to = "/index.html"
  status = 200